baseurl = "/"
languageCode = "en-us"
title = "Subhabrata Choudhury"
author = "Subhabrata Choudhury"
disqusShortname = "kanche"
[permalinks]
    posts = "/p/:year/:month/:title"
[[menu.main]]
    name = "HOME"
    identifier = "HOME"
    weight = 1
    url = "/"
[[menu.main]]
    name = "POSTS"
    identifier = "POSTS"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "ABOUT"
    identifier = "ABOUT"
    weight = 3
    url = "/about/"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        lineNos = false
        lineNumbersInTable = true
        style = "github"
        guessSyntax = true
[build]
writeStats = true
